server:
  port: 80
spring:
  application:
    name: cloud-consumer-order
  # zipkin/sleuth链路跟踪
  zipkin:
    base-url: http://127.0.0.1:9411
  sleuth:
    sampler:
      # 采样值介于0到1之间,1表示全部采集
      probability: 1
eureka:
  client:
    #    表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #      defaultZone: http://127.0.0.1:7001/eureka
      #    表示是否将自己注册进EurekaServer默认为true

      # 集群版
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka